# Generated by Django 2.2.3 on 2019-08-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('mail', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DropMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SosialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('twiiter', models.URLField(blank=True, max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('companyname', models.CharField(max_length=100)),
                ('jobname', models.CharField(max_length=100)),
                ('jobdesj', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('experience', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('jobresponsibilities', models.CharField(max_length=100)),
                ('jobskillrequirement', models.CharField(max_length=100)),
                ('endtime', models.DateTimeField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('jobsqualification', models.CharField(max_length=100)),
                ('jobcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JobCategory')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JobType')),
                ('sosialid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SosialLink')),
            ],
        ),
    ]
