# Generated by Django 2.2.3 on 2019-08-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190802_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosiallink',
            name='jobsid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sosialid', to='api.Jobs'),
        ),
    ]
