# Generated by Django 2.2.3 on 2019-08-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190802_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='twiiter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobdesj',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobresponsibilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobskillrequirement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobsqualification',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='SosialLink',
        ),
    ]
